#!/bin/sh

./main 2>&1 | stdbuf -o0 grep -iv -e '^(main:.*It *is *most *likely *synthesized *outside *Gdk/GTK+$'  -e '^(main:.*Missing *name *of *pseudo-class$' -e '^(main:.*Whoever *translated *default:LTR *did *so *wrongly.$' -e '^$'
